### ISSUE TITLE
lone (manual) test for MGRS in tester plugin fail on BD 1.1 b5 installer

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-mgrs-tools-plugin#7]
```
Test name: MGRS tools-Test MRGS tools
Test result:Test failed at step 'Load layer' with message:
global name 'os' is not defined
Traceback (most recent call last):
  File "C:/Users/boundless/.qgis2/python/plugins\qgistester\testerwidget.py", line 142, in runNextStep
    execute(step.function)
  File "C:/Users/boundless/.qgis2/python/plugins\qgistester\utils.py", line 70, in execute
    return func()
  File "C:/Users/boundless/.qgis2/python/plugins\mgrstools\tests\testerplugin.py", line 14, in _loadLayer
    layerfile = os.path.join(os.path.dirname(__file__), "data", "MGRS_100kmSQ_ID_02H.shp")
NameError: global name 'os' is not defined
```

**Comment by gioman** [comment]
error now is different (after latest commit)

```
Test name: MGRS tools-Test MRGS tools
Test result:Test failed at step 'Select map tool' with message:
global name 'plugins' is not defined
Traceback (most recent call last):
  File "C:/Users/boundless/.qgis2/python/plugins\qgistester\testerwidget.py", line 142, in runNextStep
    execute(step.function)
  File "C:/Users/boundless/.qgis2/python/plugins\qgistester\utils.py", line 70, in execute
    return func()
  File "C:/Users/boundless/.qgis2/python/plugins\mgrstools\tests\testerplugin.py", line 20, in _setTool
    plugins["mgrstools"].setTool()
NameError: global name 'plugins' is not defined
```

**Comment by alexbruy** [comment]
Should be fixed
